config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("super/", admin.site.urls),
    path("", include("pages.urls")),
    path("accounts/", include("allauth.urls")),
    path("records/", include("records.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

pages/urls.py
from django.urls import path

from .views import home_page_view, profile_page_view

app_name = ""
urlpatterns = [
    path("", home_page_view, name="home"),
    path("profile/", profile_page_view, name="profile"),
]

records/urls.py
from django.urls import path, re_path, register_converter
from django.utils.timezone import datetime

from .views import (
    export_data_view,
    record_editor_view,
    record_form_change_view,
    record_form_save_view,
    record_list_view,
)


class DateConverter:  # pragma: no cover
    regex = "\d{4}-\d{1,2}-\d{1,2}"
    format = "%Y-%m-%d"

    def to_python(self, value):
        return datetime.strptime(value, self.format).date()

    def to_url(self, value):
        return value.strftime(self.format)


register_converter(DateConverter, "date")

app_name = "records"
urlpatterns = [
    path("list/", record_list_view, name="list"),
    path("save_form/", record_form_save_view, name="save_form"),
    path("change_form/", record_form_change_view, name="change_form"),
    path("export/<str:format>/", export_data_view, name="export"),
    re_path(r"^(?P<date>\d{4}-\d{1,2}-\d{1,2})/$", record_editor_view, name="edit"),
    path("", record_editor_view, name="edit_today"),
]

templates/pages/home.html
{% extends 'base.html' %}
{% load static %}


{% block head_title %}Record A.Day - R.A.D{% endblock head_title %}


{% block content %}
<h2>Super fast daily notes.</h2>

<p>
  Write about daily reflections, achievements, or accomplishments.
</p>
<p>
  Like a <a href="https://www.intelligentchange.com/products/the-five-minute-journal">five minute journal</a> without marketing budgets and celebrity endorsements.
</p>
<img src="{% static 'images/editor_screenshot.png' %}" alt="Screenshot" style="max-width:75%;margin:auto;margin-top:1.5em;display:block;">

{% endblock content %}

templates/pages/profile.html
{% extends 'base.html' %}

{% block head_title %}Profile{% endblock head_title %}

{% block content %}
<h2>Profile</h2>
<p>Logged in as {{ user.email }}</p>

<ul>
    <li><a href="{% url 'account_change_password' %}">Change password</a></li>
    <li><a href="{% url 'account_logout' %}">Sign out</a></li>
</ul>

<hr>
<br>
<p>Change default headings for daily records below:

<form action="" method="post">
    {% csrf_token %}
    {{ record_setting_form.as_p }}
    <input type="submit" value="Update">
</form>
</p>

<hr>
<br>
<h3>Export my data</h3>
<ul>
    <li><a href="{% url 'records:export' 'csv' %}">csv</a></li>
    <li><a href="{% url 'records:export' 'json' %}">json</a></li>
</ul>
{% endblock content %}