config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("super/", admin.site.urls),
    path("", include("pages.urls")),
    path("accounts/", include("allauth.urls")),
    path("records/", include("records.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

pages/urls.py
from django.urls import path

from .views import home_page_view, profile_page_view

app_name = ""
urlpatterns = [
    path("", home_page_view, name="home"),
    path("profile/", profile_page_view, name="profile"),
]

records/urls.py
from django.urls import path, re_path, register_converter
from django.utils.timezone import datetime

from .views import (
    export_data_view,
    record_editor_view,
    record_form_change_view,
    record_form_save_view,
    record_list_view,
)


class DateConverter:  # pragma: no cover
    regex = "\d{4}-\d{1,2}-\d{1,2}"
    format = "%Y-%m-%d"

    def to_python(self, value):
        return datetime.strptime(value, self.format).date()

    def to_url(self, value):
        return value.strftime(self.format)


register_converter(DateConverter, "date")

app_name = "records"
urlpatterns = [
    path("list/", record_list_view, name="list"),
    path("save_form/", record_form_save_view, name="save_form"),
    path("change_form/", record_form_change_view, name="change_form"),
    path("export/<str:format>/", export_data_view, name="export"),
    re_path(r"^(?P<date>\d{4}-\d{1,2}-\d{1,2})/$", record_editor_view, name="edit"),
    path("", record_editor_view, name="edit_today"),
]

templates/403_csrf.html
{% extends 'base.html' %}

{% block head_title %}Forbidden (403){% endblock head_title %}

{% block content %}
<h1>Forbidden (403)</h1>
<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
  <meta name="description" content="A webapp for recording daily accomplishments, achievements, reflections, and more.">

  <title>{% block head_title %}Record my Day{% endblock head_title %}</title>

  {% block extra_head %}{% endblock extra_head %}

  <!-- Favicon -->
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon-16x16.png' %}">
  <link rel="icon" type="image/png" sizes="192x192" href="{% static 'images/android-chrome-192x192.png' %}">
  <link rel="icon" type="image/png" sizes="512x512" href="{% static 'images/android-chrome-512x512.png' %}">
  
  <!-- Stylesheets -->
  {% block css %}
  <link rel="stylesheet" href="{% static 'css/basic.css' %}">
  {% endblock %}

</head>

<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
  <header>
    <a href="{% url 'home' %}">
      <img src="{% static 'images/logo_bungee_spice.png' %}" alt="RaD Logo" style="max-height:2em;">
    </a>
    <br>
    {% block nav %}
      {% if user.is_authenticated %}
        <a href="{% url 'records:edit_today' %}">Today</a>
        <a href="{% url 'records:list' %}">All</a>
        <a href="{% url 'profile' %}">Profile</a>
      {% else %}
        <a href="{% url 'account_login' %}">Log in</a>
        <a href="{% url 'account_signup' %}">Sign up</a>
      {% endif %}
    {% endblock nav %}
  </header>
  {% block body %}
  <main>
    {% block content %}
    <p>Default content...</p>
    {% endblock content %}
  </main>
  {% endblock body %}
  {% block extra_body %}
  {% endblock extra_body %}
  <footer>
    <small>
      &copy; 2023-{% now "Y" %}
    </small>
  </footer>

  {% block javascript %}

  <!-- Project JS -->
  <script src="{% static 'js/htmx_1-8-5.js' %}"></script>

  {% endblock javascript %}

</body>

</html>